newsapp/urls.py
from django.urls import path
from .views import *

app_name = "newsapp"
urlpatterns = [
    path("",HomeView.as_view(), name="home"),
    path("contact/",ContactView.as_view(), name="contact"),
    path("about/",AboutView.as_view(), name="about"),
    path("leeza/",ProfileView.as_view(), name="profile"),
    path("nepal/",CountryView.as_view(), name="country"),
    path("news/list/",NewsListView.as_view(), name="newslist"),
    path("student/list/",StudentListView.as_view(), name="studentlist"),
    path("news/<int:pk>/detail/",NewsDetailView.as_view(), name="newsdetail"),
    path("student/<int:pk>/detail/",StudentDetailView.as_view(), name="studentdetail"),
    path("album/list/",AlbumListView.as_view(), name ="albumlist"),
    path("album/<int:pk>/detail/",AlbumDetailView.as_view(), name="albumdetail"),
    path("news/create/",NewsCreateView.as_view(), name="newscreate"),
    path("category/create/",CategoryCreateView.as_view(), name="categorycreate"),
    path("news/<int:pk>/update/",NewsUpdateView.as_view(), name="newsupdate"),
    path("student/create/",StudentCreateView.as_view(), name="studentcreate"),
    path("student/<int:pk>/update",StudentUpdateView.as_view(), name="studentupdate"),
    path("category/<int:pk>/detail/",CategoryDetailView.as_view(), name="categorydetail"),
    path("news/<int:pk>/delete/",NewsDeleteView.as_view(),name="newsdelete"),
    path("student/<int:pk>/delete/",StudentDeleteView.as_view(),name="studentdelete"),
    



]

newsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("newsapp.urls")),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

newsapp/models.py
from django.db import models
#This page is for database coding.
# Create your models here.
class Student(models.Model):
	name = models.CharField(max_length = 100)
	roll_no = models.PositiveIntegerField()
	mobile_no = models.CharField(max_length = 20)
	email = models.EmailField()
	image = models.ImageField(upload_to = 'students')
	program = models.CharField(max_length = 100)
	cv = models.FileField(upload_to ='cv')
	about = models.TextField()

	def __str__(self):
		return self.name+"("+str(self.roll_no)+")"


class Teacher(models.Model):
	name = models.CharField(max_length = 100)
	mobile_no = models.CharField(max_length = 20)
	department = models.CharField(max_length = 50)
	subject = models.CharField(max_length = 50)
	about = models.TextField()


class Category(models.Model):
	title = models.CharField(max_length = 50)
	image = models.ImageField(upload_to = 'category')

	def __str__(self):
		return self.title

class News(models.Model):
	title = models.CharField(max_length = 100)
	image = models.ImageField(upload_to = "news")
	# category = models.OneToOneField(Category, on_delete = models.CASCADE)
	# category = models.ForeignKey(Category, on_delete = models.CASCADE)
	category = models.ManyToManyField(Category)

	detail = models.TextField()
	author = models.CharField(max_length = 100)
	date = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.title

class Album(models.Model):
	title = models.CharField(max_length = 50)
	date = models.DateTimeField(auto_now_add = True)
	description = models.TextField()

	def __str__(self):
		return self.title

class Photo(models.Model):
	album = models.ForeignKey(Album,on_delete = models.CASCADE)
	image = models.ImageField(upload_to ="photo")
	caption = models.TextField(null = True, blank = True)

	def __str__(self):
		return self.album.title

newsapp/forms.py
from django import forms
from .models import *


class NewsForm(forms.ModelForm):
	class Meta:
		model = News
		fields = ['title','image','category','detail','author']

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = ['title','image']

class StudentForm(forms.ModelForm):
	class Meta:
		model = Student
		fields = "__all__"


		

newsapp/views.py
from django.views.generic import *
from .models import *
from .forms import *


class HomeView(ListView):
	template_name = "home.html"
	queryset = Category.objects.all()
	#Model = Category
	context_object_name = "myallcategory" 


class ContactView(TemplateView):
	template_name = "contact.html"


class AboutView(TemplateView):
	template_name = "about.html"


class ProfileView(TemplateView):
	template_name = "leeza.html"


class CountryView(TemplateView):
	template_name = "nepal.html"

class NewsListView(ListView):
	template_name = "newslist.html"
	queryset = News.objects.all().order_by("-id")
	context_object_name = "allnews" 

class StudentListView(ListView):
	template_name = "studentlist.html"
	queryset = Student.objects.all().order_by("-id")
	context_object_name = "allstudents"

class NewsDetailView(DetailView):
	template_name = "newsdetail.html"
	model = News
	#queryset = News.objects.all()
	context_object_name = "newsobject"

class StudentDetailView(DetailView):
	template_name = "studentdetail.html"
	model = Student
	context_object_name = "studentobject"

class AlbumListView(ListView):
	template_name = "albumlist.html"
	model = Album
	context_object_name = "allalbums"

class AlbumDetailView(DetailView):
	template_name = "albumdetail.html"
	model = Album
	context_object_name = "albumobject"

class NewsCreateView(CreateView):
	template_name = "newscreate.html"
	form_class = NewsForm
	success_url = "/news/list/"

class CategoryCreateView(CreateView):
	template_name = "categorycreate.html"
	form_class = CategoryForm
	success_url = "/"

class NewsUpdateView(UpdateView):
	template_name = "newscreate.html"
	form_class = NewsForm
	model = News
	success_url = "/news/list/"

class StudentCreateView(CreateView):
	template_name = "studentcreate.html"
	form_class = StudentForm
	model = Student
	success_url = "/student/list/"

class StudentUpdateView(UpdateView):
	template_name = "studentcreate.html"
	form_class = StudentForm
	model = Student
	success_url = "/student/list/"

class CategoryDetailView(DetailView):
	template_name = "categorydetail.html"
	model = Category
	context_object_name = "categoryobject"

class NewsDeleteView(DeleteView):
	template_name = "newsdelete.html"
	model = News
	success_url = "/news/list/"

class StudentDeleteView(DeleteView):
	template_name = "studentdelete.html"
	model = Student
	success_url = "/student/list"






		


# Create your views here.

templates/albumlist.html
{% extends 'base.html' %}
{% block title %}
Albumlist
{% endblock %}


{% block content %}
<h3>All albums</h3><hr>
{% for album in allalbums %}
<p><a href="{% url 'newsapp:albumdetail' album.id %}">{{album.title}}</a></p>


{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
		<title>{% block title %} {% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body class ="container-fluid">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Newsite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'newsapp:home' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:profile' %}">Leeza</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:country' %}">Nepal</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:newslist' %}">Newslist</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:studentlist' %}">Studentlist</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:newscreate' %}">NewsCreate</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:categorycreate' %}">Category Create</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newsapp:studentcreate' %}">Student Create</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<!--     <a href="/contact/">contact</a>
    <a href="/about/">about</a>
    <a href="/leeza/">leeza</a>
    <a href="/nepal/">nepal</a>
    <h4>Welcome to my site.</h4>

 -->    {% block content %}

    {% endblock %}

</body>
</html>

templates/categorycreate.html
{% extends 'base.html' %}
{% block title %}
Category Create
{% endblock %}

{% block content %}
<h3>Add Category</h3><hr>
<form method = "POST" enctype = "multipart/form-data">
{% csrf_token %} 
{{form.as_p}}
<button>Save Category</button>	

</form>
{% endblock %}

templates/categorydetail.html
{% extends 'base.html' %}
{% block title %}
CategoryDetail
{% endblock %}

{% block content %}
<h3>{{categoryobject.title}}</h3>
<img src="{{categoryobject.image.url}}" width="250">

{% for news in categoryobject.news_set.all %}
<li><a href="/news/{{news.id}}/detail/">{{news.title}}</a></li>
<img src="{{news.image.url}}" width="300">
{% endfor %}


{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}
Contact
{% endblock %}
{% block content %}
<h3>This is a contact page.</h3>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock %}


{% block content %}


<h3>This is a home page.</h3>


{% for category in myallcategory %}
<li><a href="{%url 'newsapp:categorydetail' category.id %}">{{category.title}}</a></li>


{% endfor %}


{% endblock %}

templates/nepal.html
{% extends 'base.html' %}
{% block title %}
Nepal
{% endblock %}
{% block content %}
<h3>Hello this is a nepal page.</h3>

{% endblock %}

templates/newscreate.html
{% extends 'base.html' %}
{% block title %}
News Create
{% endblock %}

{% block content %}
<h3>Add news</h3><hr>
<form method = "POST" enctype = "multipart/form-data">
{% csrf_token %} 
{{form.as_p}}
<button>Save News</button>	

</form>
{% endblock %}

templates/newsdetail.html
{% extends 'base.html' %}
{% block title %}
Newsdetail
{% endblock %}


{% block content %}
<h3>{{newsobject.title}}</h3>
<a href="{%url 'newsapp:newsupdate'  newsobject.id %}">Update this news</a><br>
<a href="{%url 'newsapp:newsdelete'  newsobject.id %}">Delete this news</a><br>
<img src="{{newsobject.image.url}}" width="500">
<p>{{newsobject.detail}}</p>
<hr>
<p>Author:{{newsobject.author}}</p>
<p>Date:{{newsobject.date}}</p>
{% endblock %}

templates/newslist.html
{% extends 'base.html' %}
{% block title %}
NewsList
{% endblock %}


{% block content %}
<h3>All news</h3><hr>
{% for news in allnews %}
<h4><a href="{% url 'newsapp:newsdetail' news.id %}">{{news.title}}</a></h4>
<p>Author:{{news.author}}</p>
<img src="{{news.image.url}}" width="500">

<p>{{news.date}}</p>

{% endfor %}
{% endblock %}

templates/studentcreate.html
{% extends 'base.html' %}
{% block title %}
Student Create
{% endblock %}

{% block content %}
<h3>Add Student</h3><hr>
<form method = "POST" enctype = "multipart/form-data">
{% csrf_token %} 
{{form.as_p}}
<button>Save Student</button>	

</form>
{% endblock %}

templates/studentdelete.html
{% extends 'base.html' %}
{% block title %}
Student delete
{% endblock %}}

{% block content %}
<h3>Delete Student</h3>
<form method="POST">
	{% csrf_token %}
	<h5>Do you want to delete this student?</h5>
	<button class=" btn btn-danger">Yes</button>
	<a href="/student/list/" class="btn btn-primary">No</a>
</form>
{% endblock %}

templates/studentdetail.html
{% extends 'base.html' %}
{% block title %}
StudentDetail
{% endblock %}

{% block content %}
<h3>{{studentobject.name}}</h3>
<a href="{%url 'newsapp:studentupdate'  studentobject.id %}">Update this student</a>
<a href="{%url 'newsapp:studentdelete'  studentobject.id %}">Delete this student</a>
<img src="{{studentobject.image.url}}">
<p>{{studentobject.roll_no}}</p>
<hr>
<p>{{studentobject.mobile_no}}</p>
<p>{{studentobject.email}}</p>
<p>{{studentobject.program}}</p>
<p>{{studentobject.cv}}</p>
<p>{{studentobject.about}}</p>

{% endblock %}

templates/studentlist.html
{% extends 'base.html' %}
{% block title %}
StudentList
{% endblock %}


{% block content %}
<h3>All students</h3><hr>
{% for student in allstudents %}
<h4><a href="/student/{{student.id}}/detail/">{{student.name}}({{student.id}})</a></h4>
<img src="{{student.image.url}}" width="500">
{% endfor %}
{% endblock %}